### ISSUE TITLE
Error starting due to error creating /tmp//tmux-1000 (No space left on device)

### ISSUE THREAD

**Issue by edewit** [vorburger/cloudshell#1]
I start with:
`sudo docker run --hostname=testhost -eUSER_ID=me -eUSER_PWD=password --rm -p 8080:8080 gcr.io/vorburger/github.com/vorburger/cloudshell-debian`

on `localhost:8080` I get:
![image](https://user-images.githubusercontent.com/51133/78564849-55f92f00-781d-11ea-92d0-7f21b156ea4c.png)

**Comment by vorburger** [comment]
Thanks for having tried this project out! Hm, interesting.. also curious... it "works for me". So the error is shown in the screenshot is `"error creating /tmp//tmux-1000 (No space left on device)"` ... that's nothing even directly to this container - it seems like (link!) [your docker doesn't let you write to `/tmp`](https://www.google.com/search?q=docker+error+creating+%2Ftmp+%28No+space+left+on+device%29+)? I'm not sure how that's possible... 

Do you want to try, just for a test, if something like this works (I have not actually ran this command, just made it up):

    sudo docker run --hostname=testhost --rm debian:latest echo "hello, world" >/tmp//tmux-1000

Do see what I mean and why I'm suggesting this? Does that work?

**Comment by edewit** [comment]
Yes I see, but it seems that is not the problem:
```
$> sudo docker run --hostname=testhost --rm debian:latest echo "hello, world" >/tmp//tmux-1000
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
f15005b0235f: Already exists
Digest: sha256:125ab9ab9718f4dba6c3342407bb1923afce4f6b2a12b3a502d818274db9faf9
Status: Downloaded newer image for debian:latest
$> ll /tmp/tmux-1000 
-rw-r--r--. 1 edewit edewit 13 Apr  7 15:18 /tmp/tmux-1000
$> more /tmp/tmux-1000 
hello, world

```

**Comment by edewit** [comment]
I think it has to do with user permissions on the container. I tried to create the file in the container and started and stopped it a couple of times also added `--user 1000:1000` on command line to start it and suddenly it started working. Not sure what it was.
